//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.03 at 09:17:12 PM MYT 
//


package com.azrul.chenook.workflow.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractHumanActivity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractHumanActivity">
 *   &lt;complexContent>
 *     &lt;extension base="{}BaseActivity">
 *       &lt;attribute name="handledBy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="directlySentTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="supervisoryApprovalHierarchy" type="{}StringArray" />
 *       &lt;attribute name="slaInHours" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractHumanActivity")
@XmlSeeAlso({
    HumanActivity.class,
    DirectHumanActivity.class
})
public class AbstractHumanActivity
    extends BaseActivity
{

    @XmlAttribute(name = "handledBy")
    protected String handledBy;
    @XmlAttribute(name = "directlySentTo")
    protected String directlySentTo;
    @XmlAttribute(name = "supervisoryApprovalHierarchy")
    protected List<String> supervisoryApprovalHierarchy;
    @XmlAttribute(name = "slaInHours")
    protected Integer slaInHours;

    /**
     * Gets the value of the handledBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandledBy() {
        return handledBy;
    }

    /**
     * Sets the value of the handledBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandledBy(String value) {
        this.handledBy = value;
    }

    /**
     * Gets the value of the directlySentTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectlySentTo() {
        return directlySentTo;
    }

    /**
     * Sets the value of the directlySentTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectlySentTo(String value) {
        this.directlySentTo = value;
    }

    /**
     * Gets the value of the supervisoryApprovalHierarchy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supervisoryApprovalHierarchy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupervisoryApprovalHierarchy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSupervisoryApprovalHierarchy() {
        if (supervisoryApprovalHierarchy == null) {
            supervisoryApprovalHierarchy = new ArrayList<String>();
        }
        return this.supervisoryApprovalHierarchy;
    }

    /**
     * Gets the value of the slaInHours property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSlaInHours() {
        return slaInHours;
    }

    /**
     * Sets the value of the slaInHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSlaInHours(Integer value) {
        this.slaInHours = value;
    }

}
