/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.azrul.chenook.workflow.model;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.04 at 08:05:20 PM MYT 
//



import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DirectHumanActivity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectHumanActivity">
 *   &lt;complexContent>
 *     &lt;extension base="{}HumanActivity">
 *       &lt;attribute name="directlySentTo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectHumanActivity")
public class DirectHumanActivity
    extends HumanActivity
{

    @XmlAttribute(name = "directlySentTo", required = true)
    protected String directlySentTo;

    /**
     * Gets the value of the directlySentTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectlySentTo() {
        return directlySentTo;
    }

    /**
     * Sets the value of the directlySentTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectlySentTo(String value) {
        this.directlySentTo = value;
    }

}
